import type { PeakpathData } from "./types";

// "Today" is fixed so relative timestamps and screenshots stay stable.
export const TODAY_ISO = "2026-05-21T12:00:00";

export const data: PeakpathData = {
  todayISO: TODAY_ISO,

  ytd: {
    earnings: 48320,
    deltaPct: 23,
    // Jun 2025 → May 2026. Steady summer, autumn kicker, year-end push,
    // Q1 reset, March dip, April recovery, May acceleration.
    monthlyTrend: [
      { month: "Jun '25", value: 3520 },
      { month: "Jul '25", value: 3760 },
      { month: "Aug '25", value: 4180 },
      { month: "Sep '25", value: 4820 },
      { month: "Oct '25", value: 4690 },
      { month: "Nov '25", value: 5410 },
      { month: "Dec '25", value: 5340 },
      { month: "Jan '26", value: 3210 },
      { month: "Feb '26", value: 3620 },
      { month: "Mar '26", value: 2810 },
      { month: "Apr '26", value: 5120 },
      { month: "May '26", value: 1840 },
    ],
  },

  monthlyGoal: {
    current: 8640,
    target: 12000,
    daysLeft: 10,
  },

  streak: { weeks: 12 },

  nextPayout: {
    dateISO: "2026-05-25T09:00:00",
    amount: 1840,
  },

  rank: {
    current: 6,
    delta: 2,
    region: "West Coast",
  },

  featuredProgramId: "q2-enterprise-renewals",

  programs: [
    {
      id: "q2-enterprise-renewals",
      name: "Q2 Enterprise Renewals",
      shortName: "Q2 Renewals",
      blurb: "Renew the book before quarter-end.",
      currentPayout: 2400,
      currentTier: "Silver",
      nextTier: "Gold",
      progressToNextTier: 0.26,
      endsInDays: 40,
      isFeatured: true,
    },
    {
      id: "new-logo-acceleration",
      name: "New Logo Acceleration",
      shortName: "New Logos",
      blurb: "$300 per net-new logo. Bonus at 5.",
      currentPayout: 900,
      currentTier: "Silver",
      nextTier: "Gold",
      progressToNextTier: 0.6,
      endsInDays: 40,
    },
    {
      id: "channel-partner-boost",
      name: "Channel Partner Boost",
      shortName: "Channel Boost",
      blurb: "1.5× commission on partner-sourced deals.",
      currentPayout: 1860,
      currentTier: "Silver",
      nextTier: "Gold",
      progressToNextTier: 0.41,
      endsInDays: 40,
    },
    {
      id: "healthcare-vertical",
      name: "Healthcare Vertical Expansion",
      shortName: "Healthcare",
      blurb: "Tier up at 4 healthcare deals.",
      currentPayout: 1000,
      currentTier: "Bronze",
      nextTier: "Silver",
      progressToNextTier: 0.5,
      endsInDays: 71,
    },
    {
      id: "premium-tier-upsell",
      name: "Premium Tier Upsell",
      shortName: "Premium Upsell",
      blurb: "$400 per customer moved to premium.",
      currentPayout: 1200,
      currentTier: "Silver",
      nextTier: "Gold",
      progressToNextTier: 0.3,
      endsInDays: 40,
    },
    {
      id: "q1-q2-carryover",
      name: "Q1 → Q2 Carryover Bonus",
      shortName: "Carryover",
      blurb: "$750 locked in for Q1 quota hit.",
      currentPayout: 750,
      currentTier: "Gold",
      nextTier: null,
      progressToNextTier: 1,
      endsInDays: 4,
    },
  ],

  programDetails: {
    "q2-enterprise-renewals": {
      id: "q2-enterprise-renewals",
      name: "Q2 Enterprise Renewals",
      shortName: "Q2 Renewals",
      blurb:
        "Bring every enterprise contract back across the line before June 30.",
      currentPayout: 2400,
      currentEarned: 2400,
      currentTier: "Silver",
      nextTier: "Gold",
      progressToNextTier: 0.26,
      endsInDays: 40,
      isFeatured: true,
      tiers: [
        { name: "Bronze", threshold: 500, payout: 250 },
        { name: "Silver", threshold: 1500, payout: 750 },
        { name: "Gold", threshold: 5000, payout: 2400 },
        { name: "Platinum", threshold: 10000, payout: 5500 },
      ],
      stats: {
        dealsClosed: 14,
        avgDealCommission: 380,
        conversionPct: 31,
        daysRemaining: 40,
      },
      weeklyTrend: [
        { week: "Apr 14", value: 220 },
        { week: "Apr 21", value: 340 },
        { week: "Apr 28", value: 410 },
        { week: "May 5", value: 520 },
        { week: "May 12", value: 480 },
        { week: "May 19", value: 430 },
      ],
      milestones: [
        {
          id: "m1",
          label: "First renewal closed",
          date: "Apr 3, 2026",
          status: "done",
        },
        {
          id: "m2",
          label: "Hit 5-deal milestone",
          date: "Apr 18, 2026",
          status: "done",
        },
        {
          id: "m3",
          label: "Silver tier unlocked",
          date: "May 11, 2026",
          status: "done",
        },
        {
          id: "m4",
          label: "20-deal milestone",
          date: "Projected May 28, 2026",
          status: "projected",
        },
        {
          id: "m5",
          label: "Gold tier unlocked",
          date: "Projected Jun 4, 2026",
          status: "projected",
        },
      ],
    },
  },

  // 8 events, each tied to a number you can find elsewhere.
  activity: [
    {
      id: "a1",
      iconKey: "check-circle",
      text: "Closed Acme Industries renewal — $42K. Counts toward Q2 Renewals.",
      ts: "2026-05-21T10:18:00",
      programId: "q2-enterprise-renewals",
    },
    {
      id: "a2",
      iconKey: "target",
      text: "Hit weekly demo goal — 5 demos booked.",
      ts: "2026-05-20T17:30:00",
    },
    {
      id: "a3",
      iconKey: "dollar-sign",
      text: "Payout of $1,240 processed for April commissions.",
      ts: "2026-05-19T08:00:00",
    },
    {
      id: "a4",
      iconKey: "trending-up",
      text: "Rank moved from #8 to #6 on the West Coast leaderboard.",
      ts: "2026-05-18T12:00:00",
    },
    {
      id: "a5",
      iconKey: "trophy",
      text: "Unlocked Silver tier in Q2 Enterprise Renewals.",
      ts: "2026-05-11T15:42:00",
      programId: "q2-enterprise-renewals",
    },
    {
      id: "a6",
      iconKey: "badge",
      text: "New badge earned: Renewal Whisperer.",
      ts: "2026-05-09T11:05:00",
    },
    {
      id: "a7",
      iconKey: "check-circle",
      text: "Closed Northwind Logistics — $28K, sourced via channel partner.",
      ts: "2026-05-06T14:20:00",
      programId: "channel-partner-boost",
    },
    {
      id: "a8",
      iconKey: "users",
      text: "Moved Globex Corp to premium plan — $400 upsell credit.",
      ts: "2026-05-04T10:00:00",
      programId: "premium-tier-upsell",
    },
  ],

  achievements: [
    {
      id: "ach-1",
      name: "Renewal Whisperer",
      flavor: "Closed 5 renewals in a single quarter.",
      earnedAt: "2026-05-09",
      iconKey: "handshake",
    },
    {
      id: "ach-2",
      name: "Streak Keeper",
      flavor: "Twelve weeks above target. And counting.",
      earnedAt: "2026-05-04",
      iconKey: "flame",
    },
    {
      id: "ach-3",
      name: "Comeback Kid",
      flavor: "Bounced back from a slow March with two surprise renewals.",
      earnedAt: "2026-04-29",
      iconKey: "rocket",
    },
    {
      id: "ach-4",
      name: "Pipeline Architect",
      flavor: "Built $500K of fresh pipeline in a single month.",
      earnedAt: "2026-04-22",
      iconKey: "compass",
    },
    {
      id: "ach-5",
      name: "Triple Threat Tuesday",
      flavor: "Three closes before lunch on a single Tuesday.",
      earnedAt: "2026-04-15",
      iconKey: "swords",
    },
    {
      id: "ach-6",
      name: "First Blood",
      flavor: "First deal of the quarter.",
      earnedAt: "2026-04-03",
      iconKey: "zap",
    },
    {
      id: "ach-7",
      name: "Channel Champion",
      flavor: "Hit the partner-sourced stretch goal.",
      earnedAt: "2026-03-28",
      iconKey: "users",
    },
    {
      id: "ach-8",
      name: "Quota Crusher",
      flavor: "Closed Q1 at 108% of plan.",
      earnedAt: "2026-03-31",
      iconKey: "trophy",
    },
    {
      id: "ach-9",
      name: "Demo Marathoner",
      flavor: "Ran 20 demos in a single week.",
      earnedAt: "2026-02-14",
      iconKey: "target",
    },
    {
      id: "ach-10",
      name: "Year One",
      flavor: "One year on the team. Still here. Still selling.",
      earnedAt: "2026-01-15",
      iconKey: "calendar-check",
    },
    {
      id: "ach-11",
      name: "Holiday Hustle",
      flavor: "Closed three deals between Dec 20 and Dec 31.",
      earnedAt: "2025-12-31",
      iconKey: "gift",
    },
    {
      id: "ach-12",
      name: "Top of the Heap",
      flavor: "Hit #3 on the regional leaderboard.",
      earnedAt: "2025-12-08",
      iconKey: "mountain",
    },
    {
      id: "ach-13",
      name: "Six Figures",
      flavor: "Crossed $100K career earnings.",
      earnedAt: "2025-11-22",
      iconKey: "diamond",
    },
    {
      id: "ach-14",
      name: "The Closer",
      flavor: "Closed a 6-month deal in 11 days.",
      earnedAt: "2025-11-04",
      iconKey: "shield",
    },
    {
      id: "ach-15",
      name: "Upsell Specialist",
      flavor: "Moved five customers to a higher tier in a month.",
      earnedAt: "2025-10-19",
      iconKey: "trending-up",
    },
    {
      id: "ach-16",
      name: "Quiet Powerhouse",
      flavor: "Six weeks of consistent over-quota without a slip.",
      earnedAt: "2025-09-30",
      iconKey: "leaf",
    },
    {
      id: "ach-17",
      name: "Healthcare Hero",
      flavor: "First two healthcare-vertical wins.",
      earnedAt: "2025-09-12",
      iconKey: "medal",
    },
    {
      id: "ach-18",
      name: "Five Star",
      flavor: "Five-star CSAT on a renewed contract.",
      earnedAt: "2025-08-25",
      iconKey: "star",
    },
    {
      id: "ach-19",
      name: "Crown Jewel",
      flavor: "Closed the largest deal of the month.",
      earnedAt: "2025-08-11",
      iconKey: "crown",
    },
    {
      id: "ach-20",
      name: "Fast Start",
      flavor: "First sale within two weeks of starting.",
      earnedAt: "2024-06-19",
      iconKey: "sparkles",
    },
    {
      id: "ach-21",
      name: "Cross-Sell Pro",
      flavor: "Sold three different products to the same account.",
      earnedAt: "2025-07-18",
      iconKey: "swords",
    },
    {
      id: "ach-22",
      name: "Quarter Closer",
      flavor: "Closed five deals in the final week of a quarter.",
      earnedAt: "2025-09-29",
      iconKey: "trophy",
    },
    {
      id: "ach-23",
      name: "First Renewal",
      flavor: "Renewed your first customer.",
      earnedAt: "2024-12-04",
      iconKey: "handshake",
    },
  ],

  leaderboard: [
    { rank: 1, name: "Wei Zhang", avatarSrc: "/avatars/peer-5.svg", ytdEarnings: 87410, delta: 0, territory: "San Francisco" },
    { rank: 2, name: "Tomás Reyes", avatarSrc: "/avatars/peer-6.svg", ytdEarnings: 76280, delta: 1, territory: "Los Angeles" },
    { rank: 3, name: "Aaliyah Johnson", avatarSrc: "/avatars/peer-7.svg", ytdEarnings: 68150, delta: -1, territory: "Seattle" },
    { rank: 4, name: "Jordan Martinez", avatarSrc: "/avatars/peer-1.svg", ytdEarnings: 57940, delta: 0, territory: "Phoenix" },
    { rank: 5, name: "Priya Sundaram", avatarSrc: "/avatars/peer-2.svg", ytdEarnings: 52310, delta: 1, territory: "Portland" },
    { rank: 6, name: "__CURRENT__", avatarSrc: "__CURRENT__", isCurrentUser: true, ytdEarnings: 48320, delta: 2, territory: "Los Angeles" },
    { rank: 7, name: "Sam O'Brien", avatarSrc: "/avatars/peer-3.svg", ytdEarnings: 45680, delta: -2, territory: "San Diego" },
    { rank: 8, name: "Rachel Kim", avatarSrc: "/avatars/peer-4.svg", ytdEarnings: 42190, delta: 0, territory: "Seattle" },
    { rank: 9, name: "Marcus Williams", avatarSrc: "/avatars/peer-8.svg", ytdEarnings: 39740, delta: 3, territory: "Las Vegas" },
    { rank: 10, name: "Hana Yoshida", avatarSrc: "/avatars/peer-9.svg", ytdEarnings: 37650, delta: -1, territory: "San Francisco" },
    { rank: 11, name: "Diego Cruz", avatarSrc: "/avatars/peer-10.svg", ytdEarnings: 35280, delta: 1, territory: "San Diego" },
    { rank: 12, name: "Olivia Park", avatarSrc: "/avatars/peer-11.svg", ytdEarnings: 33910, delta: 0, territory: "Los Angeles" },
    { rank: 13, name: "Brandon Lee", avatarSrc: "/avatars/peer-12.svg", ytdEarnings: 31450, delta: -3, territory: "Sacramento" },
    { rank: 14, name: "Naima Hassan", avatarSrc: "/avatars/peer-13.svg", ytdEarnings: 29830, delta: 2, territory: "Portland" },
    { rank: 15, name: "Carlos Mendoza", avatarSrc: "/avatars/peer-14.svg", ytdEarnings: 27620, delta: 0, territory: "Phoenix" },
    { rank: 16, name: "Sophie Tran", avatarSrc: "/avatars/peer-15.svg", ytdEarnings: 25410, delta: 1, territory: "San Francisco" },
    { rank: 17, name: "Ethan Walsh", avatarSrc: "/avatars/peer-16.svg", ytdEarnings: 23180, delta: -1, territory: "Denver" },
    { rank: 18, name: "Yuki Nakamura", avatarSrc: "/avatars/peer-17.svg", ytdEarnings: 21040, delta: 0, territory: "Seattle" },
    { rank: 19, name: "Andre Robinson", avatarSrc: "/avatars/peer-18.svg", ytdEarnings: 18720, delta: 4, territory: "Las Vegas" },
    { rank: 20, name: "Lila Patel", avatarSrc: "/avatars/peer-19.svg", ytdEarnings: 16450, delta: -2, territory: "Los Angeles" },
  ],
};
